/**
 * This file is a header override for arm_math.h, we only need a couple things from it. Add more here if necessary.
 */

#ifndef ARM_MATH_HEADER_OVERRIDE_H__
#define ARM_MATH_HEADER_OVERRIDE_H__

#include <stdint.h>
#include "string.h"

#define __SIMD32(addr) (*(int32_t **)&(addr))

typedef int64_t q63_t;

typedef int32_t q31_t;

typedef int16_t q15_t;

/**
 * @brief Instance structure for the Q31 FIR decimator.
 */
typedef struct
{
    uint8_t M;        /**< decimation factor. */
    uint16_t numTaps; /**< number of coefficients in the filter. */
    q31_t *pCoeffs;   /**< points to the coefficient array. The array is of length numTaps.*/
    q31_t *pState;    /**< points to the state variable array. The array is of length numTaps+blockSize-1. */
} arm_fir_decimate_instance_q31;

/**
 * @brief Error status returned by some functions in the library.
 */
typedef enum
{
    ARM_MATH_SUCCESS = 0,         /**< No error */
    ARM_MATH_ARGUMENT_ERROR = -1, /**< One or more arguments are incorrect */
    ARM_MATH_LENGTH_ERROR = -2,   /**< Length of data buffer is incorrect */
    ARM_MATH_SIZE_MISMATCH = -3,  /**< Size of matrices is not compatible with the operation. */
    ARM_MATH_NANINF = -4,         /**< Not-a-number (NaN) or infinity is generated */
    ARM_MATH_SINGULAR = -5,       /**< Generated by matrix inversion if the input matrix is singular and cannot be inverted. */
    ARM_MATH_TEST_FAILURE = -6    /**< Test Failed  */
} arm_status;

arm_status arm_fir_decimate_init_q31(
    arm_fir_decimate_instance_q31 *S,
    uint16_t numTaps,
    uint8_t M,
    q31_t *pCoeffs,
    q31_t *pState,
    uint32_t blockSize);

void arm_q31_to_q15(
    q31_t *pSrc,
    q15_t *pDst,
    uint32_t blockSize);

#endif
